import type { SpriteAsset } from './schema.ts';

/**
 * Godot 4 export. Per asset, under `<dir>/<id>/`:
 *   <id>.png   the sheet
 *   <id>.tres  SpriteFrames resource (one AtlasTexture region per frame)
 *   <id>.tscn  drop-in AnimatedSprite2D scene: nearest filtering, feet on the node origin
 *   <id>.gd    (when the sprite has hitboxes/events) keeps Hitbox/Hurtbox areas in step
 *              with the current frame and emits frame_event(name)
 */
export interface GodotFile { path: string; text?: string; binary?: Uint8Array }

const q = (s: string) => JSON.stringify(s); // Godot string literals use JSON-compatible escaping

export function godotPaths(asset: SpriteAsset, dir = 'sprites') {
  const base = `${dir.replace(/^\/+|\/+$/g, '')}/${asset.id}`;
  return {
    png: `${base}/${asset.id}.png`,
    tres: `${base}/${asset.id}.tres`,
    tscn: `${base}/${asset.id}.tscn`,
    gd: `${base}/${asset.id}.gd`,
  };
}

const hasGameData = (asset: SpriteAsset) => Object.values(asset.frameData ?? {}).some(m => m.hitboxes.length || m.hurtboxes.length || m.events.length);

/**
 * The frame-data script: per animation, per frame, the hit/hurt rectangles (frame pixels)
 * and events. On every frame change it reshapes the Hitbox/Hurtbox collision shapes
 * (mirrored when flip_h) and emits frame_event for each event.
 */
export function frameDataScript(asset: SpriteAsset): string {
  const rect = (b: { x: number; y: number; w: number; h: number }) => `Rect2(${b.x}, ${b.y}, ${b.w}, ${b.h})`;
  const data = asset.animations.map(a => {
    const frames = a.frames.map(i => {
      const m = asset.frameData?.[String(i)];
      return `{"hit": [${(m?.hitboxes ?? []).map(rect).join(', ')}], "hurt": [${(m?.hurtboxes ?? []).map(rect).join(', ')}], "events": [${(m?.events ?? []).map(q).join(', ')}]}`;
    });
    return `\t${q(a.name)}: [\n\t\t${frames.join(',\n\t\t')}\n\t],`;
  }).join('\n');
  return [
    'extends AnimatedSprite2D',
    `## Generated by Kinetome for "${asset.name.replace(/"/g, '')}": hitboxes, hurtboxes and frame events.`,
    '## Connect to frame_event to play sounds, spawn effects or deal damage on the right frame.',
    '',
    'signal frame_event(name: StringName)',
    '',
    `const FRAME_W := ${asset.frameWidth}`,
    'const DATA := {',
    data,
    '}',
    '',
    '@onready var hitbox: Area2D = $Hitbox',
    '@onready var hurtbox: Area2D = $Hurtbox',
    '',
    'func _ready() -> void:',
    '\tframe_changed.connect(_on_frame)',
    '\tanimation_changed.connect(_on_frame)',
    '\t_on_frame()',
    '',
    'func _on_frame() -> void:',
    '\tvar frames: Array = DATA.get(String(animation), [])',
    '\tvar f: Dictionary = frames[frame] if frame < frames.size() else {}',
    '\t_fill(hitbox, f.get("hit", []))',
    '\t_fill(hurtbox, f.get("hurt", []))',
    '\tfor e in f.get("events", []):',
    '\t\tframe_event.emit(StringName(e))',
    '',
    'func _fill(area: Area2D, rects: Array) -> void:',
    '\tvar shapes: Array = area.get_children().filter(func(n): return n is CollisionShape2D)',
    '\twhile shapes.size() < rects.size():',
    '\t\tvar s := CollisionShape2D.new()',
    '\t\ts.shape = RectangleShape2D.new()',
    '\t\tarea.add_child(s)',
    '\t\tshapes.append(s)',
    '\tfor i in shapes.size():',
    '\t\tvar s: CollisionShape2D = shapes[i]',
    '\t\tif i < rects.size():',
    '\t\t\tvar r: Rect2 = rects[i]',
    '\t\t\tvar x := FRAME_W - r.position.x - r.size.x if flip_h else r.position.x',
    '\t\t\t(s.shape as RectangleShape2D).size = r.size',
    '\t\t\ts.position = offset + Vector2(x, r.position.y) + r.size / 2.0',
    '\t\t\ts.set_deferred("disabled", false)',
    '\t\telse:',
    '\t\t\ts.set_deferred("disabled", true)',
    '',
  ].join('\n');
}

export function spriteFramesTres(asset: SpriteAsset, pngResPath: string): string {
  const used = [...new Set(asset.animations.flatMap(a => a.frames))].sort((a, b) => a - b);
  const subId = (i: number) => `AtlasTexture_f${i}`;
  const out: string[] = [];
  out.push(`[gd_resource type="SpriteFrames" load_steps=${used.length + 2} format=3]`, '');
  out.push(`[ext_resource type="Texture2D" path=${q(pngResPath)} id="1_sheet"]`, '');
  for (const i of used) {
    const r = asset.frames[i];
    out.push(`[sub_resource type="AtlasTexture" id="${subId(i)}"]`);
    out.push('atlas = ExtResource("1_sheet")');
    out.push(`region = Rect2(${r.x}, ${r.y}, ${r.w}, ${r.h})`, '');
  }
  const anims = asset.animations.map(a => [
    '{',
    `"frames": [${a.frames.map(i => `{\n"duration": 1.0,\n"texture": SubResource("${subId(i)}")\n}`).join(', ')}],`,
    `"loop": ${a.loop},`,
    `"name": &${q(a.name)},`,
    `"speed": ${a.fps.toFixed(1)}`,
    '}',
  ].join('\n'));
  out.push('[resource]', `animations = [${anims.join(', ')}]`, '');
  return out.join('\n');
}

export function animatedSpriteTscn(asset: SpriteAsset, tresResPath: string, scriptResPath?: string): string {
  const first = asset.animations.find(a => /idle/i.test(a.name)) ?? asset.animations[0];
  const nodeName = asset.name.replace(/[^A-Za-z0-9_]+/g, '') || 'Sprite';
  // centered = false + integer offset keeps pixels on the grid; the feet (pivot) sit on the node origin.
  const lines = [
    `[gd_scene load_steps=${scriptResPath ? 3 : 2} format=3]`, '',
    `[ext_resource type="SpriteFrames" path=${q(tresResPath)} id="1_frames"]`,
    ...(scriptResPath ? [`[ext_resource type="Script" path=${q(scriptResPath)} id="2_data"]`] : []),
    '',
    `[node name=${q(nodeName)} type="AnimatedSprite2D"]`,
    'texture_filter = 1',
    'sprite_frames = ExtResource("1_frames")',
  ];
  if (first) lines.push(`animation = &${q(first.name)}`, `autoplay = ${q(first.name)}`);
  lines.push('centered = false', `offset = Vector2(${-asset.pivot.x}, ${-(asset.pivot.y + 1)})`);
  if (scriptResPath) {
    // the script fills these with one CollisionShape2D per box as frames change
    lines.push('script = ExtResource("2_data")', '', '[node name="Hitbox" type="Area2D" parent="."]', '', '[node name="Hurtbox" type="Area2D" parent="."]');
  }
  lines.push('');
  return lines.join('\n');
}

export function godotFiles(asset: SpriteAsset, png: Uint8Array, dir = 'sprites'): GodotFile[] {
  const p = godotPaths(asset, dir);
  const data = hasGameData(asset);
  return [
    { path: p.png, binary: png },
    { path: p.tres, text: spriteFramesTres(asset, `res://${p.png}`) },
    { path: p.tscn, text: animatedSpriteTscn(asset, `res://${p.tres}`, data ? `res://${p.gd}` : undefined) },
    ...(data ? [{ path: p.gd, text: frameDataScript(asset) }] : []),
  ];
}
